#!/bin/sh

run_exec () {
    CMD="/storage/gpfs_data/dampe/users/ecatanzani/MyRepos/DAMPE/Stuff/DAMPE-GAcceptance/SubmitJob/ToNode/ExeSW/Release/JGAcceptance"; echo ${CMD}; ${CMD};
}

echo "`whoami` @ `hostname` : `pwd`"

CMD="source /storage/gpfs_data/dampe/users/ecatanzani/MyRepos/DAMPE/Stuff/DAMPE-GAcceptance/SubmitJob/ToNode/.bash_profile"; echo ${CMD}; ${CMD};

echo " ------------------------ "
echo " ---------- ENVS -------- "
echo " ------------------------ "
echo ""
env
echo ""
echo " ------------------------ "
echo " ------------------------ "
echo ""

HOME=`pwd`
UNIQUE="$$_$RANDOM"
SANDBOX=/data/$UNIQUE
while [[ -d $SANDBOX ]]; do
    UNIQUE="$$_$RANDOM"
    SANDBOX=/data/$UNIQUE
    echo "Searching for a free SandBox dir !"
done
mkdir -vp $SANDBOX
cd $SANDBOX
pwd

run_exec

ls -altrh
mv -v *.root /storage/gpfs_data/dampe/users/ecatanzani/MyRepos/DAMPE/Stuff/DAMPE-GAcceptance/SubmitJob/ToNode/JobResults
rm -rfv "$SANDBOX"

